### ISSUE TITLE
cannot getCookie, return null

### ISSUE THREAD

**Issue by akyong** [Grails-Plugin-Consortium/grails-cookie#3]
i am usin grail 3.1.1

i am trying to use cookie in grails 3. i tried this plugin but i don't know why its not work at all..

`cookieService.setCookie('username', customer?.email)`

and i use this code for call it from gsp

`<g:cookie name="username"/>`

i also tried this way..

`def cokusername = cookieService.setCookie('username', customer?.email)
                println "cookieService.getCookie('username')  = "+cookieService.getCookie('username')
                redirect(controller: "toko",cokusername: cokusername)`

and this is in my tokoController.groovy index :

`def index={
        def toko = CifLogo.executeQuery("from CifLogo order by rand()",[max: 10])
        def awdf = cookieService.getCookie('username')
        println "awdf = "+awdf
        println "cokusername = "+params.cokusername
        [tokoList:toko,cokusername:awdf]
    }`

i have no idea to retrieve my cookie. :( 

![Image of Yaktocat](https://i.stack.imgur.com/uk9Sy.png)

i also try this way too..

`def index(){
        def toko = CifLogo.executeQuery("from CifLogo order by rand()",[max: 10])
        def awdf = cookieService.getCookie('username')
        println "awdf = "+awdf
        println "cokusername = "+params.cokusername
        [tokoList:toko,cokusername:awdf]
    }`

![after](https://i.stack.imgur.com/eqhMk.png)

**Comment by akyong** [comment]
http://stackoverflow.com/questions/42676118/how-to-use-cookie-in-grails-3

**Comment by stokito** [comment]
It was resolved
